In [1]:
import numpy as np


Escalar (tensor 0D)

In [2]:
x=np.array(23) #Vector con un elemento 
x

array(23)

In [3]:
x.ndim

0

Vector (tensor 1D)

In [4]:
x=np.array([12,24,36,48]) #Vector con varios elementos
x


array([12, 24, 36, 48])

In [5]:
x.ndim

1

Matriz (tensor 2D)

In [6]:
z = np.array([[5,78,24,1], [1,2,3,4], [4,6,7,8]])
z


array([[ 5, 78, 24,  1],
       [ 1,  2,  3,  4],
       [ 4,  6,  7,  8]])

In [7]:
z.ndim

2

Tensores 3D

In [8]:
 q = np.random.randn(3,4,2) # Creamos de forma aleatoria una matriz de matrices
 q

array([[[-1.07120357,  2.14034136],
        [ 1.79960727,  0.91060995],
        [-0.77691485, -0.24986309],
        [-0.3685973 , -0.29235503]],

       [[-0.63063802,  2.95974854],
        [ 1.08931797, -0.38573205],
        [ 0.46346374,  0.86522236],
        [-1.66340574,  0.41329666]],

       [[ 0.44159164,  0.08391042],
        [ 0.35886973, -1.94435216],
        [-0.16498786, -1.43549155],
        [ 0.95642629,  0.40329861]]])

In [9]:
q.ndim

3